// Generated by LiveScript 1.2.0
/**
 * User: kmandrup
 * Date: 26/08/14
 * Time: 16:03
 */
(function(){
  var Immutable, DataWrap;
  Immutable = require('immutable');
  DataWrap = {
    immutable: function(data){
      return Immutable.fromJS(data);
    },
    wrap: function(data){
      return this.immutable(data);
    }
  };
  module.exports = DataWrap;
}).call(this);
