// Generated by LiveScript 1.2.0
/**
 * User: kmandrup
 * Date: 26/08/14
 * Time: 13:24
 */
(function(){
  var ListModelManager, FirebaseSyncManager;
  ListModelManager = (function(){
    ListModelManager.displayName = 'ListModelManager';
    var prototype = ListModelManager.prototype, constructor = ListModelManager;
    function ListModelManager(list, firebase_ref, path, class_name){
      this.list = list;
      this.firebase_ref = firebase_ref;
      this.path = path;
      this.class_name = class_name;
      this.list_ref = this.synced_list().reference;
    }
    prototype.sync_store = function(){
      return new SyncStore(this.class_name);
    };
    prototype.sync_changes = function(){
      return new SyncManager(this.class_name, this.list, this.list_ref).sync_changes();
    };
    prototype.synced_list = function(){
      return this._synced_list || (this._synced_list = new SyncedList(this.firebase_ref, this.path, this.class_name));
    };
    prototype.wrap_local_crud_ops = function(){
      return new ListExtender(this.list, this.list_ref, this.sync_store()).wrap_crud();
    };
    prototype.config = function(){
      this.sync_changes();
      this.wrap_local_crud_ops();
      return this.list;
    };
    return ListModelManager;
  }());
  FirebaseSyncManager = (function(){
    FirebaseSyncManager.displayName = 'FirebaseSyncManager';
    var prototype = FirebaseSyncManager.prototype, constructor = FirebaseSyncManager;
    function FirebaseSyncManager(firebase_ref, path){
      this.firebase_ref = firebase_ref;
      this.path = path != null ? path : '';
    }
    prototype.list_model_manager = function(){
      return new ListModelManager(this.list, this.firebase_ref, this.path, this.class_name);
    };
    prototype.getSynchronizedArray = function(class_name, list){
      this.class_name = class_name;
      this.list = list != null
        ? list
        : [];
      return this.list_model_manager().config();
    };
    return FirebaseSyncManager;
  }());
  new FirebaseSyncManager;
}).call(this);
