// Generated by LiveScript 1.2.0
/**
 * User: kmandrup
 * Date: 26/08/14
 * Time: 14:18
*/
(function(){
  var SyncedList;
  SyncedList = (function(){
    SyncedList.displayName = 'SyncedList';
    var prototype = SyncedList.prototype, constructor = SyncedList;
    function SyncedList(fb, path, class_name){
      this.fb = fb;
      this.path = path;
      this.class_name = class_name;
      this.set_class_name();
      this.set_reference();
    }
    prototype.set_class_name = function(){
      var last_path;
      if (!this.class_name) {
        last_path || (last_path = _.last(_.split('/', this.path)));
        if (_.empty(last_path)) {
          throw new Error("Class name can't be resolved from path: " + this.path + " or className: " + this.class_name);
        }
        return this.class_name = require('inflector').singularize(last_path);
      }
    };
    prototype.set_reference = function(){
      return this.reference = this.fb.child(this.path);
    };
    return SyncedList;
  }());
}).call(this);
